Fixed icon markup
rebel1324/NutScript pull request #366
Opened 2021-02-01 21:37 UTC by Zoephix

2021-02-02 02:49 UTC, Heyter commented
https://wiki.facepunch.com/gmod/table.getn

2021-02-02 09:27 UTC, TovarischPootis requested changes
getn is depricated, use Count for non-sequential tables instead

2021-02-02 09:27 UTC, TovarischPootis commented on gamemode/core/libs/cl_markup.lua
> +		text_block.colour = colour_stack[ table.getn(colour_stack) ]
```suggestion
		text_block.colour = colour_stack[ table.Count(colour_stack) ]
```

2021-02-02 09:27 UTC, TovarischPootis commented on gamemode/core/libs/cl_markup.lua
> +		text_block.font = font_stack[ table.getn(font_stack) ]
```suggestion
		text_block.font = font_stack[ table.Count(font_stack) ]
```

2021-02-02 12:39 UTC, Heyter commented
table.Count slower that "operator #"
"#colour_stack"

2021-02-02 12:44 UTC, TovarischPootis commented
> table.Count slower than "operator #"
> "#colour_stack"

The tables in question are non-sequential ({r = #, g = #, b = #, a = #}).
# wouldn’t work, hence table.Count is needed instead

2021-02-02 13:04 UTC, Heyter commented
> > table.Count slower than "operator #"
> > "#colour_stack"
> 
> The tables in question are non-sequential ({r = #, g = #, b = #, a = #}).
> `#` wouldn’t work, hence table.Count is needed instead

Is this prank?

`local colour_stack = { {r=255,g=255,b=255,a=255} }
table.insert(colour_stack, {r=255,g=255,b=255,a=255})
print(#colour_stack)`

Output: 2

2021-02-02 13:13 UTC, TovarischPootis commented
You’re right, I was looking at the wrong thing. # works better here. My bad

2021-02-03 16:51 UTC, TovarischPootis requested changes

2021-02-03 16:51 UTC, TovarischPootis commented on gamemode/core/libs/cl_markup.lua
> +		text_block.colour = colour_stack[ table.Count(colour_stack) ]
```suggestion
		text_block.colour = colour_stack[#colour_stack ]
```
As pointed out by Heyter, # is even better here

2021-02-03 16:51 UTC, TovarischPootis commented on gamemode/core/libs/cl_markup.lua
> +		text_block.font = font_stack[ table.Count(font_stack) ]
```suggestion
		text_block.font = font_stack[ #font_stack ]
```
As pointed out by Heyter, # is even better here

2021-02-08 07:46 UTC, TovarischPootis commented
This is fine now, fixes an ancient bug with NS

2021-02-11 12:02 UTC, merged